import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ChevronRight, User, Car, FileText, CheckCircle, Loader2, AlertTriangle } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { AdminLayout } from '@/components/admin/AdminLayout';

type Step = 'cliente' | 'vehiculo' | 'orden' | 'confirmado';

const PASOS = [
    { id: 'cliente', label: 'Cliente', icon: User },
    { id: 'vehiculo', label: 'Vehículo', icon: Car },
    { id: 'orden', label: 'Orden', icon: FileText },
];

// Real DB: prioridad check (NORMAL, URGENTE)
const PRIORIDADES = ['NORMAL', 'URGENTE'];

export function NuevaOrdenPage() {
    const navigate = useNavigate();
    const [step, setStep] = useState<Step>('cliente');
    const [saving, setSaving] = useState(false);
    const [errorMsg, setErrorMsg] = useState<string | null>(null);

    const [clienteId, setClienteId] = useState<string | null>(null);
    const [vehiculoId, setVehiculoId] = useState<string | null>(null);
    const [nuevaOrdenCodigo, setNuevaOrdenCodigo] = useState('');

    // Cliente form — solo 'nombres' (un campo, nombre completo)
    const [cNombres, setCNombres] = useState('');
    const [cTel, setCTel] = useState('');
    const [clienteBusqueda, setClienteBusqueda] = useState('');
    const [clientesEncontrados, setClientesEncontrados] = useState<any[]>([]);
    const [buscandoCliente, setBuscandoCliente] = useState(false);

    // Vehículo form
    const [vPlaca, setVPlaca] = useState('');
    const [vMarca, setVMarca] = useState('');
    const [vModelo, setVModelo] = useState('');
    const [vAnio, setVAnio] = useState('');
    const [vColor, setVColor] = useState('');

    // Orden form
    const [oPrioridad, setOPrioridad] = useState('NORMAL');
    const [oFechaEst, setOFechaEst] = useState('');
    const [oNotasPublicas, setONotasPublicas] = useState('');
    const [oNotasInternas, setONotasInternas] = useState('');

    // ── Buscar cliente existente ──────────────────────────────────────────────
    const buscarCliente = async () => {
        if (clienteBusqueda.length < 2) return;
        setBuscandoCliente(true);
        const { data } = await supabase
            .from('clientes')
            .select('id, nombres, telefono, email')
            .or(`nombres.ilike.%${clienteBusqueda}%,telefono.ilike.%${clienteBusqueda}%`)
            .limit(5);
        setClientesEncontrados(data ?? []);
        setBuscandoCliente(false);
    };

    // ── Guardar cliente nuevo ─────────────────────────────────────────────────
    const guardarCliente = async () => {
        setErrorMsg(null);
        if (!cNombres.trim()) {
            setErrorMsg('El nombre completo es obligatorio.');
            return;
        }
        setSaving(true);
        const { data, error } = await supabase
            .from('clientes')
            .insert({
                nombres: cNombres.trim(),
                telefono: cTel || null,
            })
            .select('id')
            .single();
        setSaving(false);
        if (error) { setErrorMsg('Error al guardar el cliente: ' + error.message); return; }
        setClienteId(data.id);
        setStep('vehiculo');
    };

    // ── Guardar vehículo ──────────────────────────────────────────────────────
    const guardarVehiculo = async () => {
        setErrorMsg(null);
        if (!vPlaca.trim() || !vMarca.trim()) {
            setErrorMsg('Placa y marca son obligatorios.');
            return;
        }
        setSaving(true);
        const { data, error } = await supabase
            .from('vehiculos')
            .insert({
                placa: vPlaca.trim().toUpperCase(),
                marca: vMarca.trim(),
                modelo: vModelo.trim() || null,
                anio: vAnio ? parseInt(vAnio) : null,
                color: vColor || null,
                cliente_id: clienteId,
            })
            .select('id')
            .single();
        setSaving(false);
        if (error) { setErrorMsg('Error al guardar el vehículo: ' + error.message); return; }
        setVehiculoId(data.id);
        setStep('orden');
    };

    // ── Guardar orden ─────────────────────────────────────────────────────────
    const guardarOrden = async () => {
        setErrorMsg(null);
        setSaving(true);
        const { data, error } = await supabase
            .from('ordenes')
            .insert({
                cliente_id: clienteId,
                vehiculo_id: vehiculoId,
                prioridad: oPrioridad,
                fecha_estimada: oFechaEst || null,
                notas_publicas: oNotasPublicas || null,
                notas_internas: oNotasInternas || null,
                share_enabled: true,
                // codigo is auto-generated by DB trigger
            })
            .select('codigo, id')
            .single();
        setSaving(false);
        if (error) { setErrorMsg('Error al crear la orden: ' + error.message); return; }
        setNuevaOrdenCodigo(data.codigo);
        setStep('confirmado');
    };

    return (
        <AdminLayout>
            <div className="max-w-xl mx-auto space-y-6">
                <div>
                    <h1 className="text-2xl font-bold text-[#0B1220] tracking-tight">Nueva Orden</h1>
                    <p className="text-sm text-[rgba(11,18,32,0.50)] mt-0.5">Ingresa un vehículo al taller</p>
                </div>

                {/* Stepper */}
                {step !== 'confirmado' && (
                    <div className="flex items-center gap-2">
                        {PASOS.map((p, i) => {
                            const done = (step === 'vehiculo' && i === 0) || (step === 'orden' && i <= 1);
                            const active = p.id === step;
                            return (
                                <div key={p.id} className="flex items-center gap-2 flex-1">
                                    <div className={`flex items-center gap-1.5 text-xs font-semibold px-3 py-1.5 rounded-full transition-all ${active ? 'text-white' : done ? 'text-[#FF5100]' : 'text-[rgba(11,18,32,0.40)] bg-[rgba(15,23,42,0.05)]'}`}
                                        style={active ? { background: '#FF5100' } : done ? { background: 'rgba(255,81,0,0.10)' } : {}}>
                                        <p.icon className="w-3 h-3" />
                                        {p.label}
                                    </div>
                                    {i < PASOS.length - 1 && <ChevronRight className="w-3 h-3 text-[rgba(11,18,32,0.25)] flex-shrink-0" />}
                                </div>
                            );
                        })}
                    </div>
                )}

                {errorMsg && (
                    <div className="flex items-center gap-2 px-4 py-3 rounded-xl text-sm text-[#EF4444]"
                        style={{ background: 'rgba(239,68,68,0.08)', border: '1px solid rgba(239,68,68,0.15)' }}>
                        <AlertTriangle className="w-4 h-4 flex-shrink-0" />{errorMsg}
                    </div>
                )}

                {/* ── PASO 1: CLIENTE ───────────────────────────────────────── */}
                {step === 'cliente' && (
                    <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="card space-y-5" style={{ padding: '24px' }}>
                        <h2 className="text-sm font-semibold text-[#0B1220]">Datos del cliente</h2>

                        {/* Búsqueda */}
                        <div className="space-y-2">
                            <label className="form-label">¿Cliente existente?</label>
                            <div className="flex gap-2">
                                <input
                                    value={clienteBusqueda}
                                    onChange={e => setClienteBusqueda(e.target.value)}
                                    onKeyDown={e => e.key === 'Enter' && buscarCliente()}
                                    placeholder="Buscar por nombre o teléfono..."
                                    className="input-field flex-1"
                                />
                                <button onClick={buscarCliente} disabled={buscandoCliente} className="btn-secondary text-sm px-4">
                                    {buscandoCliente ? <Loader2 className="w-4 h-4 animate-spin" /> : 'Buscar'}
                                </button>
                            </div>
                            {clientesEncontrados.length > 0 && (
                                <div className="border border-[rgba(15,23,42,0.08)] rounded-xl overflow-hidden bg-white">
                                    {clientesEncontrados.map(c => (
                                        <button
                                            key={c.id}
                                            onClick={() => { setClienteId(c.id); setStep('vehiculo'); }}
                                            className="w-full text-left px-4 py-3 text-sm hover:bg-[rgba(15,23,42,0.03)] transition-colors flex items-center justify-between border-b border-[rgba(15,23,42,0.06)] last:border-0"
                                        >
                                            <span className="font-medium text-[#0B1220]">{c.nombres}</span>
                                            <span className="text-[rgba(11,18,32,0.40)] text-xs">{c.telefono}</span>
                                        </button>
                                    ))}
                                </div>
                            )}
                        </div>

                        <div className="border-t border-[rgba(15,23,42,0.07)] pt-4 space-y-4">
                            <p className="form-label">O registra uno nuevo</p>
                            <div>
                                <label className="form-label">Nombre completo *</label>
                                <input value={cNombres} onChange={e => setCNombres(e.target.value)} placeholder="Jandry Saritama" className="input-field" />
                            </div>
                            <div>
                                <label className="form-label">Teléfono</label>
                                <input value={cTel} onChange={e => setCTel(e.target.value)} placeholder="0989575378" className="input-field" />
                            </div>
                            <button onClick={guardarCliente} disabled={saving} className="btn-primary w-full flex items-center justify-center gap-2">
                                {saving ? <Loader2 className="w-4 h-4 animate-spin" /> : <>Registrar y continuar <ChevronRight className="w-4 h-4" /></>}
                            </button>
                        </div>
                    </motion.div>
                )}

                {/* ── PASO 2: VEHÍCULO ──────────────────────────────────────── */}
                {step === 'vehiculo' && (
                    <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="card space-y-5" style={{ padding: '24px' }}>
                        <h2 className="text-sm font-semibold text-[#0B1220]">Datos del vehículo</h2>
                        <div className="grid grid-cols-2 gap-3">
                            <div className="col-span-2">
                                <label className="form-label">Placa *</label>
                                <input value={vPlaca} onChange={e => setVPlaca(e.target.value)} placeholder="ABC-1234" className="input-field font-mono uppercase" />
                            </div>
                            <div>
                                <label className="form-label">Marca *</label>
                                <input value={vMarca} onChange={e => setVMarca(e.target.value)} placeholder="Toyota" className="input-field" />
                            </div>
                            <div>
                                <label className="form-label">Modelo</label>
                                <input value={vModelo} onChange={e => setVModelo(e.target.value)} placeholder="Corolla" className="input-field" />
                            </div>
                            <div>
                                <label className="form-label">Año</label>
                                <input value={vAnio} onChange={e => setVAnio(e.target.value)} placeholder="2020" className="input-field" maxLength={4} />
                            </div>
                            <div>
                                <label className="form-label">Color</label>
                                <input value={vColor} onChange={e => setVColor(e.target.value)} placeholder="Rojo" className="input-field" />
                            </div>
                        </div>
                        <div className="flex gap-3">
                            <button onClick={() => setStep('cliente')} className="btn-secondary flex-1">← Volver</button>
                            <button onClick={guardarVehiculo} disabled={saving} className="btn-primary flex-1 flex items-center justify-center gap-2">
                                {saving ? <Loader2 className="w-4 h-4 animate-spin" /> : <>Continuar <ChevronRight className="w-4 h-4" /></>}
                            </button>
                        </div>
                    </motion.div>
                )}

                {/* ── PASO 3: ORDEN ─────────────────────────────────────────── */}
                {step === 'orden' && (
                    <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="card space-y-5" style={{ padding: '24px' }}>
                        <h2 className="text-sm font-semibold text-[#0B1220]">Datos de la orden</h2>
                        <div className="grid grid-cols-2 gap-3">
                            <div>
                                <label className="form-label">Prioridad</label>
                                <select value={oPrioridad} onChange={e => setOPrioridad(e.target.value)} className="input-field">
                                    {PRIORIDADES.map(p => <option key={p} value={p}>{p}</option>)}
                                </select>
                            </div>
                            <div>
                                <label className="form-label">Fecha estimada de entrega</label>
                                <input value={oFechaEst} onChange={e => setOFechaEst(e.target.value)} type="date" className="input-field" />
                            </div>
                        </div>
                        <div>
                            <label className="form-label">Descripción del trabajo (visible al cliente)</label>
                            <textarea value={oNotasPublicas} onChange={e => setONotasPublicas(e.target.value)} rows={3} placeholder="Ej: Reparación de capó, pintura completa..." className="input-field resize-none" />
                        </div>
                        <div>
                            <label className="form-label">Notas internas (solo admin)</label>
                            <textarea value={oNotasInternas} onChange={e => setONotasInternas(e.target.value)} rows={2} placeholder="Observaciones del taller..." className="input-field resize-none" />
                        </div>
                        <div className="flex gap-3">
                            <button onClick={() => setStep('vehiculo')} className="btn-secondary flex-1">← Volver</button>
                            <button onClick={guardarOrden} disabled={saving} className="btn-primary flex-1 flex items-center justify-center gap-2">
                                {saving ? <Loader2 className="w-4 h-4 animate-spin" /> : '✓ Crear Orden'}
                            </button>
                        </div>
                    </motion.div>
                )}

                {/* ── CONFIRMADO ────────────────────────────────────────────── */}
                {step === 'confirmado' && (
                    <motion.div initial={{ opacity: 0, scale: 0.96 }} animate={{ opacity: 1, scale: 1 }} className="card text-center space-y-4" style={{ padding: '40px 32px' }}>
                        <div className="w-14 h-14 rounded-2xl flex items-center justify-center mx-auto"
                            style={{ background: 'rgba(22,163,74,0.10)' }}>
                            <CheckCircle className="w-7 h-7 text-[#16A34A]" />
                        </div>
                        <h2 className="text-2xl font-bold text-[#0B1220]">¡Orden creada!</h2>
                        <p className="text-sm text-[rgba(11,18,32,0.50)]">Código de seguimiento generado:</p>
                        <p className="font-mono-code text-4xl font-bold text-[#FF5100]">{nuevaOrdenCodigo}</p>
                        <div className="flex gap-3 pt-2">
                            <button onClick={() => navigate('/admin/dashboard')} className="btn-secondary flex-1">Ver Dashboard</button>
                            <button onClick={() => { setStep('cliente'); setClienteId(null); setVehiculoId(null); setCNombres(''); setVPlaca(''); }} className="btn-primary flex-1">
                                Nueva orden
                            </button>
                        </div>
                    </motion.div>
                )}
            </div>
        </AdminLayout>
    );
}
